# Generated by Django 5.1.4 on 2025-01-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_portfolioproject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_files/'),
        ),
    ]
