# Generated by Django 5.1.4 on 2025-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(
                blank=True, default='portfolio_images/default-image.jpg', null=True, upload_to='portfolio_images/'),
        ),
    ]
