# Generated by Django 5.1.4 on 2025-01-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_inquiry_replied_inquiry_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='reply',
            new_name='reply_message',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='design_file',
        ),
    ]
