# Generated by Django 5.1.4 on 2025-01-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_reply_inquiry_reply_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
